// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYmWAdwNqDvFBpDbuI5UrzdH4zRj8azUI',
    appId: '1:132663016346:web:b88c46ae88a53074135823',
    messagingSenderId: '132663016346',
    projectId: 'finalproject-team1',
    authDomain: 'finalproject-team1.firebaseapp.com',
    storageBucket: 'finalproject-team1.appspot.com',
    measurementId: 'G-WXP8KTWKSK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu9v7--yup8ITywLm7XFwYt6CsrWg42tQ',
    appId: '1:132663016346:android:c3432708335f8e43135823',
    messagingSenderId: '132663016346',
    projectId: 'finalproject-team1',
    storageBucket: 'finalproject-team1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf_3U7SSdmt82n1x0-8kiHURndSCnXiVM',
    appId: '1:132663016346:ios:872922ebb196f405135823',
    messagingSenderId: '132663016346',
    projectId: 'finalproject-team1',
    storageBucket: 'finalproject-team1.appspot.com',
    iosClientId: '132663016346-cq0mqkqd7rokkuqe0npm2g9sm64kcvgf.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf_3U7SSdmt82n1x0-8kiHURndSCnXiVM',
    appId: '1:132663016346:ios:872922ebb196f405135823',
    messagingSenderId: '132663016346',
    projectId: 'finalproject-team1',
    storageBucket: 'finalproject-team1.appspot.com',
    iosClientId: '132663016346-cq0mqkqd7rokkuqe0npm2g9sm64kcvgf.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );
}
